package com.nanonaitor.banking;
import net.minecraft.inventory.*;
import net.minecraft.entity.player.*;
import net.minecraft.item.ItemStack;
import net.minecraft.util.NonNullList;
public final class BankMenu extends Container {
 private final InventoryBasic display=new InventoryBasic("Bank",false,54);
 private final BankData.Account account;private final BankerEntity banker;public int page,pages=1,capacity=162;public final int[] counts=new int[54];
 public BankMenu(InventoryPlayer inv,BankerEntity b){banker=b;account=inv.player.world.isRemote?null:BankData.get(inv.player.world).account(inv.player.getUniqueID());for(int i=0;i<54;i++)addSlotToContainer(new Slot(display,i,8+i%9*18,36+i/9*18){@Override public boolean isItemValid(ItemStack s){return false;}@Override public boolean canTakeStack(EntityPlayer p){return false;}});for(int r=0;r<3;r++)for(int c=0;c<9;c++)addSlotToContainer(new Slot(inv,c+r*9+9,8+c*18,166+r*18));for(int c=0;c<9;c++)addSlotToContainer(new Slot(inv,c,8+c*18,224));refresh();}
 private void refresh(){if(account==null)return;capacity=account.capacity();pages=(account.extent()+53)/54;page=Math.min(page,pages-1);for(int i=0;i<54;i++){BankData.Entry e=account.items.get(page*54+i);counts[i]=e==null?0:e.count;display.setInventorySlotContents(i,e==null?ItemStack.EMPTY:e.item.copy());}}
 @Override public void detectAndSendChanges(){refresh();super.detectAndSendChanges();for(IContainerListener l:listeners){l.sendWindowProperty(this,0,page);l.sendWindowProperty(this,1,pages);l.sendWindowProperty(this,2,capacity);for(int i=0;i<54;i++)l.sendWindowProperty(this,3+i,counts[i]);}}
 @Override public void updateProgressBar(int id,int v){if(id==0)page=v;else if(id==1)pages=v;else if(id==2)capacity=v;else if(id<57)counts[id-3]=v;}
 @Override public boolean canInteractWith(EntityPlayer p){return banker.isEntityAlive()&&p.getDistanceSq(banker)<64;}
 @Override public boolean enchantItem(EntityPlayer p,int id){if(!canInteractWith(p)||id<0||id>1)return false;page=Math.max(0,Math.min(pages-1,page+(id==0?-1:1)));detectAndSendChanges();return true;}
 @Override public ItemStack slotClick(int slot,int button,ClickType type,EntityPlayer p){if(slot>=0&&slot<54){if(account==null||!canInteractWith(p))return ItemStack.EMPTY;int n=page*54+slot;ItemStack held=p.inventory.getItemStack();if(type==ClickType.QUICK_MOVE)return transferStackInSlot(p,slot);if(type==ClickType.PICKUP){if(held.isEmpty()){BankData.Entry e=account.items.get(n);p.inventory.setItemStack(account.take(n,e==null?0:button==1?(e.count+1)/2:e.count));}else account.deposit(n,held,button==1?1:held.getCount());}detectAndSendChanges();return ItemStack.EMPTY;}return super.slotClick(slot,button,type,p);}
 @Override public ItemStack transferStackInSlot(EntityPlayer p,int index){if(account==null||!canInteractWith(p)||index<0||index>=inventorySlots.size())return ItemStack.EMPTY;if(index<54){int n=page*54+index;BankData.Entry e=account.items.get(n);if(e==null)return ItemStack.EMPTY;int room=0;for(ItemStack s:p.inventory.mainInventory)if(s.isEmpty())room+=e.item.getMaxStackSize();else if(ItemStack.areItemsEqual(s,e.item)&&ItemStack.areItemStackTagsEqual(s,e.item))room+=Math.max(0,s.getMaxStackSize()-s.getCount());while(room>0&&account.items.containsKey(n)){ItemStack take=account.take(n,room);room-=take.getCount();p.inventory.addItemStackToInventory(take);}}else{ItemStack s=inventorySlots.get(index).getStack();for(int i=0;i<account.capacity()&&!s.isEmpty();i++)if(account.items.containsKey(i))account.deposit(i,s,s.getCount());for(int i=0;i<account.capacity()&&!s.isEmpty();i++)account.deposit(i,s,s.getCount());}detectAndSendChanges();return ItemStack.EMPTY;}
}
